print("            x")
print("           x x")
print("          x   x")
print("         x     x")
print("        x       x")
print("       x         x")
print("     x             x")
print("   x                 x")
print("x                       x")

